trigger:
  branches:
    include:
      - main  # Runs the pipeline when code is pushed to 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Runs the pipeline on a Linux VM

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '11'
      jdkArchitecture: 'x64'
      jdkSource: 'PreInstalled'

  - script: |
      mvn clean install
    displayName: 'Build Application'

  - task: Docker@2
    inputs:
      command: 'build'
      Dockerfile: '**/Dockerfile'
      tags: 'latest'
