# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main  # Runs the pipeline when code is pushed to 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Runs the pipeline on a Linux VM

steps:
  - task: UseJavaVersion@1
    inputs:
      versionSpec: '11'
      jdkArchitecture: 'x64'

  - script: |
      mvn clean install
    displayName: 'Build Application'

  - task: Docker@2
    inputs:
      command: 'build'
      Dockerfile: '**/Dockerfile'
      tags: 'latest'

  - task: Kubernetes@1
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscriptionEndpoint: '<YOUR_AZURE_SUBSCRIPTION>'
      azureResourceGroup: '<YOUR_RESOURCE_GROUP>'
      kubernetesCluster: '<YOUR_AKS_CLUSTER>'
      command: 'apply'
      arguments: '-f k8s/deployment.yaml'
