name: CI/CD Pipeline

on: [push, pull_request]  # Runs on every push or PR

jobs:
  build:
    runs-on: ubuntu-latest  # Uses a Linux virtual machine

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Pulls the code from GitHub

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker Image
        run: |
          docker build -t myapp:latest -f ./Dockerfile .
